### ISSUE TITLE
FirebaseArray crashes when it is sorted and the last element changes

### ISSUE THREAD

**Issue by ghowen** [ConnorDCrawford/FirebaseDatabaseUI#2]
Thanks for the project! It helped my a lot as Google's implementation does not support filtering and it being written in Obj-C makes it hard for me to extend.

While working with your code I discovered one bug:

If a FirebaseArray is sorted and the last element changes, the code crashes with an IndexOutOfBound exception. 

I have submitted PR #1  to fix this.

Best regards

Georg

**Comment by ConnorDCrawford** [comment]
Thanks for fixing that Georg. I'll merge your PR shortly.

To be honest, I made this framework for my own usage and never expected anyone else to actually use it. So I'm very glad it's been useful for you!

Best,
Connor

**Comment by ghowen** [comment]
Thanks Conor. Actually I am currently testing out a subclass of FirebaseArray that allows indexed queries (like an SQL join). If you are interested I can create a PR once it is finished. 

FirebaseUI from Google allows indexed queries, but they do not support filtering and sorting. And they need an IndexedTableViewDataSource, IndexedCollectionViewDataSource and an IndexedArray class for this. With your architecture an IndexedFirebaseArray is all you need, which you then can plug into the data source.

**Comment by ConnorDCrawford** [comment]
I would greatly appreciate it if you did a PR of that when you are finished. Thanks Georg.
