### ISSUE TITLE
Does FirebaseModel need to inherit from / conform to AnyObject?

### ISSUE THREAD

**Issue by ghowen** [ConnorDCrawford/FirebaseDatabaseUI#3]
Hi Connor, 

I was just trying to make a struct conform to FirebaseModel and noticed that FirebaseModel inherits from AnyObject. I removed this inheritance in a project that is heavily using the library and everything seems to work fine. Is there any reason why you implemented it this way or can it safely be removed?

Thanks.

**Comment by ConnorDCrawford** [comment]
Hi Georg,

I believe I made FirebaseModel conform to AnyObject for Objective-C interoperability. But that seems pretty unimportant in 2017. You should be able to safely remove the AnyObject conformance.

**Comment by ghowen** [comment]
Great, thanks.
